# Generated by Django 6.0.3 on 2026-08-07 00:55

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckinRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discomfort', models.IntegerField(help_text='이명 불편도 (1: 편안함 ~ 5: 매우 불편함)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('tension', models.IntegerField(help_text='긴장도 (1: 안정됨 ~ 5: 매우 불안함)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('sleep_hours', models.FloatField(blank=True, help_text='어젯밤 수면시간(시간)', null=True)),
                ('fatigue', models.IntegerField(blank=True, help_text='현재 피로도 (1~5, 선택)', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('stress', models.IntegerField(blank=True, help_text='현재 스트레스 (1~5, 선택)', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('caffeine', models.BooleanField(default=False, help_text='늦은 카페인 섭취 여부')),
                ('note', models.CharField(blank=True, default='', help_text='한 줄 메모 (선택)', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkins', to='accounts.anonymoususer')),
            ],
            options={
                'verbose_name': '야간 체크인 기록',
                'verbose_name_plural': '야간 체크인 기록 목록',
                'ordering': ['-created_at'],
            },
        ),
    ]
