# Generated by Django 6.0.3 on 2026-08-07 01:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkin', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkinrecord',
            name='sleep_hours',
            field=models.FloatField(blank=True, help_text='어젯밤 수면시간(시간)', null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
