# Generated by Django 6.0.3 on 2026-08-12 20:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkin', '0002_alter_checkinrecord_sleep_hours'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkinrecord',
            name='caffeine',
        ),
        migrations.RemoveField(
            model_name='checkinrecord',
            name='fatigue',
        ),
        migrations.RemoveField(
            model_name='checkinrecord',
            name='stress',
        ),
        migrations.AddField(
            model_name='checkinrecord',
            name='daily_factors',
            field=models.JSONField(blank=True, default=list, help_text="DailyFactor 값들의 리스트. 예: ['caffeine', 'stress']. 없으면 빈 배열"),
        ),
        migrations.AlterField(
            model_name='checkinrecord',
            name='tension',
            field=models.IntegerField(help_text='불안 정도 (1: 안정됨 ~ 5: 매우 불안함)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
