# Generated by Django 6.0.3 on 2026-08-06 01:52

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnonymousUser',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, help_text='익명 사용자 식별값 (디바이스에 저장되어 재사용됨)', primary_key=True, serialize=False)),
                ('nickname', models.CharField(blank=True, default='', max_length=50)),
                ('health_data_connected', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_accessed_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '익명 사용자',
                'verbose_name_plural': '익명 사용자 목록',
                'ordering': ['-last_accessed_at'],
            },
        ),
        migrations.CreateModel(
            name='UsageRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accessed_at', models.DateTimeField(auto_now_add=True)),
                ('device_info', models.CharField(blank=True, default='', max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usage_records', to='accounts.anonymoususer')),
            ],
            options={
                'verbose_name': '이용(재접속) 기록',
                'verbose_name_plural': '이용(재접속) 기록 목록',
                'ordering': ['-accessed_at'],
            },
        ),
    ]
