# Generated by Django 6.0.3 on 2026-08-16 17:01

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SoundFitSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('round_number', models.PositiveSmallIntegerField(default=1)),
                ('current_axis', models.CharField(choices=[('texture', 'Texture'), ('layer_mix', 'Layer Mix')], default='texture', max_length=20)),
                ('rounds', models.JSONField(blank=True, default=list)),
                ('texture', models.CharField(blank=True, choices=[('soft', '부드럽게'), ('balanced', '균형 있게'), ('clear', '선명하게')], max_length=20, null=True)),
                ('layer_mix', models.CharField(blank=True, choices=[('low', '자연음 위주'), ('medium', '균형'), ('high', '노이즈 위주')], max_length=20, null=True)),
                ('confirm_started', models.BooleanField(default=False)),
                ('done', models.BooleanField(default=False)),
                ('abandoned', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='soundfit_sessions', to='accounts.anonymoususer')),
            ],
            options={
                'verbose_name': 'Sound Fit 세션',
                'verbose_name_plural': 'Sound Fit 세션 목록',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SoundFitProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texture', models.CharField(choices=[('soft', '부드럽게'), ('balanced', '균형 있게'), ('clear', '선명하게')], max_length=20)),
                ('layer_mix', models.CharField(choices=[('low', '자연음 위주'), ('medium', '균형'), ('high', '노이즈 위주')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='soundfit_profile', to='accounts.anonymoususer')),
                ('source_session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='soundfit.soundfitsession')),
            ],
            options={
                'verbose_name': 'My Sound Profile',
                'verbose_name_plural': 'My Sound Profile 목록',
            },
        ),
        migrations.AddIndex(
            model_name='soundfitsession',
            index=models.Index(fields=['user', '-created_at'], name='soundfit_so_user_id_431898_idx'),
        ),
    ]
