# Generated by Django 6.0.3 on 2026-08-15 18:46

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RelaxationSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('activity_type', models.CharField(choices=[('thought_distancing', '생각 거리두기'), ('tension_release', '30초 긴장 해제'), ('attention_shift', '1분 주의 옮기기'), ('none', '개입 없음')], db_index=True, max_length=32)),
                ('recommendation_source', models.CharField(choices=[('rule_based', '규칙 기반'), ('personalized', '개인화(과거 결과 반영)')], default='rule_based', max_length=16)),
                ('status', models.CharField(choices=[('recommended', '추천됨(시작 전)'), ('in_progress', '진행중'), ('completed', '완료'), ('skipped', '건너뜀'), ('cancelled', '중단')], db_index=True, default='recommended', max_length=16)),
                ('tinnitus_discomfort', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('anxiety', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('stress', models.BooleanField(default=False)),
                ('fatigue', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('caffeine', models.BooleanField(default=False)),
                ('recommended_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relaxation_sessions', to='accounts.anonymoususer')),
            ],
            options={
                'verbose_name': '이완 세션',
                'verbose_name_plural': '이완 세션 목록',
                'ordering': ['-recommended_at'],
                'indexes': [models.Index(fields=['user', '-recommended_at'], name='relaxtion_r_user_id_1fa570_idx'), models.Index(fields=['user', 'activity_type', 'status'], name='relaxtion_r_user_id_09ab78_idx')],
            },
        ),
    ]
