# Generated by Django 6.0.3 on 2026-08-10 10:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TinnitusProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tone_type', models.CharField(choices=[('high', '삐— 한 음이 선명하게 들려요'), ('low', '윙— 중심이 되는 울림이 있어요'), ('wide', '쉬익— 소리가 넓게 퍼져 들려요'), ('multiple', '여러 소리가 함께 들려요')], max_length=20)),
                ('primary_tone_type', models.CharField(blank=True, choices=[('high', '삐— 한 음이 선명하게 들려요'), ('low', '윙— 중심이 되는 울림이 있어요'), ('wide', '쉬익— 소리가 넓게 퍼져 들려요'), ('multiple', '여러 소리가 함께 들려요')], help_text='tone_type이 multiple일 때만 사용. HIGH/LOW/WIDE 중 하나', max_length=20, null=True)),
                ('location', models.CharField(blank=True, max_length=100, null=True)),
                ('occurrence_times', models.JSONField(blank=True, default=list, help_text="OccurrenceTime 값들의 리스트. 예: ['night', 'quiet']")),
                ('existing_coping', models.TextField(blank=True, help_text='기존에 시도해본 대처 방법 (자유 텍스트, 추후 선택형으로 전환 가능)', null=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tinnitus_profile', to='accounts.anonymoususer')),
            ],
            options={
                'verbose_name': '이명 프로필',
                'verbose_name_plural': '이명 프로필',
            },
        ),
        migrations.CreateModel(
            name='PitchMatchSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tinnitus_type', models.CharField(choices=[('tonal', 'Tonal'), ('noise_like', 'Noise-like')], max_length=20)),
                ('range_min', models.FloatField(default=250.0, help_text='Hz, 현재 범위 하한(L)')),
                ('range_max', models.FloatField(default=16000.0, help_text='Hz, 현재 범위 상한(H)')),
                ('round_number', models.PositiveSmallIntegerField(default=1)),
                ('freq_a', models.FloatField(blank=True, null=True)),
                ('freq_b', models.FloatField(blank=True, null=True)),
                ('rounds', models.JSONField(blank=True, default=list)),
                ('provisional_center', models.FloatField(blank=True, null=True)),
                ('octave_test_started', models.BooleanField(default=False)),
                ('octave_selection', models.CharField(blank=True, choices=[('half', 'f/2'), ('same', 'f'), ('double', '2f')], max_length=10, null=True)),
                ('octave_check_limited', models.BooleanField(default=False)),
                ('done', models.BooleanField(default=False)),
                ('center_frequency', models.FloatField(blank=True, null=True)),
                ('lower_bound', models.FloatField(blank=True, null=True)),
                ('upper_bound', models.FloatField(blank=True, null=True)),
                ('octave_corrected', models.BooleanField(default=False)),
                ('abandoned', models.BooleanField(default=False)),
                ('abandoned_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pitch_match_sessions', to='accounts.anonymoususer')),
            ],
            options={
                'verbose_name': '음역 매칭 세션',
                'verbose_name_plural': '음역 매칭 세션',
                'indexes': [models.Index(fields=['user', '-created_at'], name='tinnitus_pi_user_id_822dd0_idx')],
            },
        ),
    ]
