# Generated by Django 6.0.3 on 2026-08-12 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tinnitus', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tinnitusprofile',
            name='primary_tone_type',
            field=models.CharField(blank=True, choices=[('high', '삐— 한 음이 선명하게 들려요'), ('low', '윙— 중심이 되는 울림이 있어요'), ('wide', '쉬익— 소리가 넓게 퍼져 들려요'), ('multiple', '여러 소리가 함께 들려요')], help_text='tone_type이 multiple일 때만 사용. high/low/wide 중 하나', max_length=20, null=True),
        ),
    ]
