# Generated by Django 6.0.3 on 2026-08-13 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tinnitus', '0002_alter_tinnitusprofile_primary_tone_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='pitchmatchsession',
            name='mixing_point_gain',
            field=models.FloatField(blank=True, help_text='음역 매칭 중 사용자가 이명이 덮인다고 느낀 지점의 gain 값', null=True),
        ),
    ]
