# Generated by Django 6.0.3 on 2026-08-06 14:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OnboardingStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confirmed', models.BooleanField(default=False, help_text='진단·치료 서비스가 아님을 확인했는지 여부')),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('done', models.BooleanField(default=False)),
                ('done_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='onboarding_status', to='accounts.anonymoususer')),
            ],
            options={
                'verbose_name': '온보딩 진행 상태',
                'verbose_name_plural': '온보딩 진행 상태 목록',
            },
        ),
        migrations.CreateModel(
            name='SafetyCheckResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hearing_loss', models.BooleanField(default=False, help_text='갑작스러운 청력 저하')),
                ('one_sided', models.BooleanField(default=False, help_text='한쪽에서만 지속되는 이명')),
                ('pulse_sound', models.BooleanField(default=False, help_text='맥박에 맞춰 들리는 소리')),
                ('dizziness', models.BooleanField(default=False, help_text='심한 어지럼증 동반')),
                ('need_doctor', models.BooleanField(default=False, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='safety_checks', to='accounts.anonymoususer')),
            ],
            options={
                'verbose_name': '안전 확인 응답',
                'verbose_name_plural': '안전 확인 응답 목록',
                'ordering': ['-created_at'],
            },
        ),
    ]
