# Generated by Django 6.0.3 on 2026-08-12 21:19

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FallbackSound',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('file_url', models.URLField(help_text='CDN/스토리지 상의 완성 오디오 파일 경로')),
                ('duration_seconds', models.PositiveIntegerField()),
                ('loopable', models.BooleanField(default=True)),
                ('matched_freq_min_hz', models.PositiveIntegerField()),
                ('matched_freq_max_hz', models.PositiveIntegerField()),
                ('tags', models.JSONField(blank=True, default=list, help_text="예: ['pink_noise','rain','low_variation']")),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SoundSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('status', models.CharField(choices=[('generating', '생성 중'), ('ready', '생성 완료'), ('failed_fallback', '생성 실패 - 예비 사운드로 대체'), ('playing', '재생 중'), ('paused', '일시정지'), ('completed', '정상 종료'), ('stopped_early', '중도 종료'), ('discomfort_stopped', '불편 신고로 중단')], default='generating', max_length=32)),
                ('input_snapshot', models.JSONField(help_text='이명 음역, 사운드 선호, 현재 불편도/긴장도, 최근 수면·스트레스, 과거 도움/불편 평가 등')),
                ('generated_params', models.JSONField(blank=True, help_text='frequency_bands, sources, mix_ratio, modulation_intensity, duration_minutes, fade_out_seconds 등', null=True)),
                ('explanation_reasons', models.JSONField(blank=True, default=list, help_text='실제 반영된 핵심 근거 1~3개, 단정적 표현 금지 문구 리스트')),
                ('recommended_duration_minutes', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('is_fallback', models.BooleanField(default=False)),
                ('generation_error_code', models.CharField(blank=True, max_length=64)),
                ('playback_started_at', models.DateTimeField(blank=True, null=True)),
                ('playback_ended_at', models.DateTimeField(blank=True, null=True)),
                ('total_played_seconds', models.PositiveIntegerField(default=0)),
                ('end_reason', models.CharField(blank=True, choices=[('timer', '종료 타이머'), ('fade_complete', '페이드아웃 완료'), ('user_stop', '사용자 즉시 종료'), ('discomfort', '불편 신고'), ('sleep_onset', '추정 입면 시각 도달')], max_length=32)),
                ('initial_volume', models.FloatField(default=0.2, help_text='0.0~1.0, 최초 재생 시 적용하는 초기 gain 값')),
                ('max_volume_applied', models.FloatField(blank=True, null=True)),
                ('mixing_point_gain', models.FloatField(blank=True, help_text='혼합점 탐색 중 사용자가 선택한 gain 값 (0.0~0.6)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fallback_sound', models.ForeignKey(blank=True, help_text='F-612: 실제로 재생에 쓰인 예비 사운드(사운드 생성에 실패했을 때), 또는 F-613: 생성 성공 시에도 미리 캐싱해두는 예비 사운드 후보', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='sound.fallbacksound')),
                ('regenerated_from', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='regenerations', to='sound.soundsession')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sound_sessions', to='accounts.anonymoususer')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SoundDiscomfortReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reasons', models.JSONField(default=list, help_text='Reason 값의 리스트 (복수 선택 가능)')),
                ('note', models.CharField(blank=True, max_length=200)),
                ('follow_up_action', models.CharField(blank=True, choices=[('regenerate', '다시 생성하기'), ('switch_previous', '이전에 편안했던 사운드로 전환'), ('end_session', '오늘은 세션 마치기')], max_length=32, null=True)),
                ('reported_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discomfort_reports', to='sound.soundsession')),
            ],
            options={
                'ordering': ['-reported_at'],
            },
        ),
        migrations.AddIndex(
            model_name='soundsession',
            index=models.Index(fields=['user', '-created_at'], name='sound_sound_user_id_1a03c4_idx'),
        ),
        migrations.AddIndex(
            model_name='soundsession',
            index=models.Index(fields=['session_id'], name='sound_sound_session_758138_idx'),
        ),
    ]
