# Generated by Django 6.0.3 on 2026-08-13 02:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sound', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='soundsession',
            name='explanation_reasons',
        ),
        migrations.AlterField(
            model_name='fallbacksound',
            name='matched_freq_max_hz',
            field=models.PositiveIntegerField(help_text='이 예비 사운드가 대응하는 이명 음역의 상한 Hz'),
        ),
        migrations.AlterField(
            model_name='fallbacksound',
            name='matched_freq_min_hz',
            field=models.PositiveIntegerField(help_text='이 예비 사운드가 대응하는 이명 음역의 하한 Hz'),
        ),
        migrations.AlterField(
            model_name='fallbacksound',
            name='tags',
            field=models.JSONField(blank=True, default=list, help_text="예비 사운드의 특징 태그. 예: ['pink_noise', 'rain', 'low_variation']"),
        ),
        migrations.AlterField(
            model_name='sounddiscomfortreport',
            name='follow_up_action',
            field=models.CharField(blank=True, choices=[('regenerate', '다른 사운드로 바꾸기'), ('switch_previous', '이전에 편안했던 사운드로 전환'), ('end_session', '오늘은 세션 마치기')], max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='sounddiscomfortreport',
            name='reasons',
            field=models.JSONField(default=list, help_text='Reason 값의 리스트'),
        ),
        migrations.AlterField(
            model_name='soundsession',
            name='fallback_sound',
            field=models.ForeignKey(blank=True, help_text='사용자 음역·선호와 가장 가까운 예비 사운드 후보. is_fallback=True인 경우 실제 재생에 사용되는 예비 사운드.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='sound.fallbacksound'),
        ),
        migrations.AlterField(
            model_name='soundsession',
            name='mixing_point_gain',
            field=models.FloatField(blank=True, help_text='혼합점 탐색 중 사용자가 선택한 gain 값', null=True),
        ),
        migrations.AlterField(
            model_name='soundsession',
            name='status',
            field=models.CharField(choices=[('generating', '생성 중'), ('ready', '재생 준비 완료'), ('generation_failed', '사운드 생성 실패'), ('playing', '재생 중'), ('paused', '일시정지'), ('completed', '정상 종료'), ('stopped_early', '중도 종료'), ('discomfort_stopped', '불편 신고로 중단')], default='generating', max_length=32),
        ),
    ]
