# Generated by Django 6.0.3 on 2026-08-13 02:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sound', '0002_remove_soundsession_explanation_reasons_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fallbacksound',
            options={'verbose_name': '예비 사운드', 'verbose_name_plural': '예비 사운드 목록'},
        ),
        migrations.AlterModelOptions(
            name='sounddiscomfortreport',
            options={'ordering': ['-reported_at'], 'verbose_name': '사운드 불편 신고', 'verbose_name_plural': '사운드 불편 신고 목록'},
        ),
        migrations.AlterModelOptions(
            name='soundsession',
            options={'ordering': ['-created_at'], 'verbose_name': '사운드 세션', 'verbose_name_plural': '사운드 세션 목록'},
        ),
    ]
