# Generated by Django 6.0.3 on 2026-08-13 03:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sound', '0003_alter_fallbacksound_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='soundsession',
            name='mixing_point_gain',
        ),
    ]
