# Generated by Django 6.0.3 on 2026-08-15 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sound', '0004_remove_soundsession_mixing_point_gain'),
    ]

    operations = [
        migrations.AddField(
            model_name='soundsession',
            name='final_params',
            field=models.JSONField(blank=True, help_text='사용자가 최종적으로 재생한 사운드 설정', null=True),
        ),
    ]
