# Generated by Django 6.0.3 on 2026-08-17 17:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sound', '0005_soundsession_final_params'),
    ]

    operations = [
        migrations.AlterField(
            model_name='soundsession',
            name='fallback_sound',
            field=models.ForeignKey(blank=True, help_text='사용자 음역 및 과거 불편 사유를 기준으로 선택한 예비 사운드 후보 is_fallback=True인 경우 실제 재생에 사용되는 예비 사운드.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='sound.fallbacksound'),
        ),
        migrations.AlterField(
            model_name='soundsession',
            name='input_snapshot',
            field=models.JSONField(help_text='이명 음역 및 혼합점, personalization 사운드 전략, Sound Fit fallback 값, 과거 불편 사유 등'),
        ),
    ]
