# Generated by Django 6.0.3 on 2026-08-17 01:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPersonalizationProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sound_tag_weights', models.JSONField(blank=True, default=dict, help_text='사용자의 평가 결과를 기반으로 계산된 사운드 태그별 개인화 가중치')),
                ('excluded_sound_tags', models.JSONField(blank=True, default=list, help_text='반복적으로 불편 평가된 사운드 특성. 다음 사운드 후보 생성 시 제외 또는 감점한다.')),
                ('relaxation_type_weights', models.JSONField(blank=True, default=dict, help_text='사용자의 평가 및 완료/중단 결과를 기반으로 계산한 이완 활동 종류별 개인화 가중치')),
                ('discouraged_relaxation_types', models.JSONField(blank=True, default=list, help_text='반복적으로 낮은 도움 평가 또는 불편 반응이 있었던 이완 활동 유형. 다음 후보 선택 시 감점 대상으로 사용한다.')),
                ('evaluation_sample_count', models.PositiveIntegerField(default=0, help_text='전체 개인화 학습에 반영된 평가 개수')),
                ('sound_sample_count', models.PositiveIntegerField(default=0, help_text='사운드 선호 학습에 반영된 평가 개수')),
                ('relaxation_sample_count', models.PositiveIntegerField(default=0, help_text='이완 활동 선호 학습에 반영된 평가 개수')),
                ('last_updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='personalization_profile', to='accounts.anonymoususer')),
            ],
            options={
                'verbose_name': '사용자 개인화 프로필',
                'verbose_name_plural': '사용자 개인화 프로필 목록',
            },
        ),
        migrations.CreateModel(
            name='InterventionDecision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state_snapshot', models.JSONField(help_text='이명 프로필, 음역 범위, 오늘 체크인, 최근 건강 데이터, 과거 개입 결과 등을 하나로 통합한 현재 상태 스냅샷')),
                ('has_sufficient_data', models.BooleanField(default=False, help_text='개인화 판단에 충분한 데이터가 확보되었는지 여부. 부족하면 개인 학습보다 초기 규칙을 우선한다.')),
                ('missing_data_sources', models.JSONField(blank=True, default=list, help_text='현재 상태 객체를 생성할 때 값이 없어 사용하지 못한 데이터 출처 목록')),
                ('intervention_type', models.CharField(choices=[('sound_only', '사운드만'), ('sound_with_relaxation', '사운드 + 이완 병행'), ('none', '개입 없음')], db_index=True, max_length=32)),
                ('sound_strategy', models.JSONField(blank=True, default=dict, help_text='personalization이 선택한 고수준 사운드 전략. 실제 frequency_bands, notch filter, mixing ramp 등의 DSP 파라미터는 sound 앱에서 계산한다.')),
                ('relaxation_activity_type', models.CharField(blank=True, help_text='사운드와 병행하도록 선택한 이완 활동 종류. relaxtion 앱의 RelaxationType 값을 문자열로 저장한다.', max_length=32, null=True)),
                ('reason', models.TextField(blank=True, help_text='개인화 결정 근거를 내부 분석용으로 저장. 사용자에게 그대로 노출하는 설명문은 아님.')),
                ('sound_session_id', models.PositiveIntegerField(blank=True, null=True)),
                ('relaxation_session_id', models.PositiveIntegerField(blank=True, null=True)),
                ('decided_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intervention_decisions', to='accounts.anonymoususer')),
            ],
            options={
                'verbose_name': '개입 결정',
                'verbose_name_plural': '개입 결정 목록',
                'ordering': ['-decided_at'],
                'indexes': [models.Index(fields=['user', '-decided_at'], name='personaliza_user_id_a6bffe_idx'), models.Index(fields=['user', 'intervention_type'], name='personaliza_user_id_4c51a7_idx')],
            },
        ),
    ]
