# Generated by Django 6.0.3 on 2026-08-18 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personalization', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='interventiondecision',
            name='relaxation_recommendation_source',
            field=models.CharField(blank=True, choices=[('rule_based', '규칙 기반'), ('personalized', '개인화')], help_text='이완 활동이 현재 상태 규칙 그대로 선택되었는지, 과거 개인화 결과에 의해 보정되었는지 기록한다.', max_length=16, null=True),
        ),
    ]
