# Generated by Django 6.0.3 on 2026-08-18 02:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personalization', '0002_interventiondecision_relaxation_recommendation_source'),
        ('relaxtion', '0001_initial'),
        ('sound', '0006_alter_soundsession_fallback_sound_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interventiondecision',
            name='relaxation_session_id',
        ),
        migrations.RemoveField(
            model_name='interventiondecision',
            name='sound_session_id',
        ),
        migrations.AddField(
            model_name='interventiondecision',
            name='relaxation_session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='intervention_decisions', to='relaxtion.relaxationsession'),
        ),
        migrations.AddField(
            model_name='interventiondecision',
            name='sound_session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='intervention_decisions', to='sound.soundsession'),
        ),
    ]
