# Generated by Django 6.0.3 on 2026-08-21 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personalization', '0003_remove_interventiondecision_relaxation_session_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='interventiondecision',
            name='ai_display_summary',
            field=models.TextField(blank=True, help_text='AI가 생성한 사용자 노출용 자연어 설명.'),
        ),
        migrations.AddField(
            model_name='interventiondecision',
            name='ai_display_tags',
            field=models.JSONField(blank=True, default=list, help_text="AI 분석 리포트에서 사용자에게 보여줄 태그 목록. 예: ['강한 노이즈 불편', '파도 선호', '피로']"),
        ),
    ]
