# Generated by Django 6.0.3 on 2026-08-16 21:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checkin_reminder_enabled', models.BooleanField(default=False, help_text='취침 전 체크인 알림 사용 여부')),
                ('checkin_reminder_time', models.TimeField(blank=True, help_text='체크인 알림 시각', null=True)),
                ('result_reminder_enabled', models.BooleanField(default=False, help_text='다음날 결과 기록 알림 사용 여부')),
                ('result_reminder_time', models.TimeField(blank=True, help_text='결과 기록 알림 시각', null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_settings', to='accounts.anonymoususer')),
            ],
            options={
                'verbose_name': '알림 설정',
                'verbose_name_plural': '알림 설정 목록',
            },
        ),
    ]
