# Generated by Django 6.0.3 on 2026-08-10 00:49

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InterventionEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intervention_type', models.CharField(choices=[('sound', '사운드'), ('relaxation', '이완 활동')], max_length=20)),
                ('session_id', models.PositiveIntegerField(help_text='intervention_type에 해당하는 세션 모델의 PK (아직 실제 FK 아님)')),
                ('discomfort_after', models.PositiveSmallIntegerField(blank=True, help_text='개입 후 이명 불편도 (1~5)', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('tension_after', models.PositiveSmallIntegerField(blank=True, help_text='개입 후 긴장도 (1~5)', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('helpfulness', models.CharField(blank=True, choices=[('helpful', '도움됨'), ('no_change', '변화 없음'), ('uncomfortable', '불편함')], max_length=20, null=True)),
                ('discomfort_feedback', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', '대기 중'), ('evaluated', '평가 완료'), ('skipped', '건너뜀'), ('expired', '미응답(24시간 경과)')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('evaluated_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intervention_evaluations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '개입 후 피드백',
                'verbose_name_plural': '개입 후 피드백',
                'indexes': [models.Index(fields=['user', 'status'], name='feedback_in_user_id_40b7fe_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'intervention_type', 'session_id'), name='feedback_one_evaluation_per_session')],
            },
        ),
    ]
