# Generated by Django 6.0.3 on 2026-08-09 02:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='interventionevaluation',
            options={'verbose_name': '개입 후 피드백', 'verbose_name_plural': '개입 후 피드백'},
        ),
    ]
