# Generated by Django 6.0.3 on 2026-08-10 01:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='interventionevaluation',
            options={'verbose_name': '개입 후 피드백', 'verbose_name_plural': '개입 후 피드백'},
        ),
        migrations.RemoveIndex(
            model_name='interventionevaluation',
            name='feedback_in_user_id_dbcecb_idx',
        ),
        migrations.AddField(
            model_name='interventionevaluation',
            name='status',
            field=models.CharField(choices=[('pending', '대기 중'), ('evaluated', '평가 완료'), ('skipped', '건너뜀'), ('expired', '미응답(24시간 경과)')], default='pending', max_length=20),
        ),
        migrations.AddIndex(
            model_name='interventionevaluation',
            index=models.Index(fields=['user', 'status'], name='feedback_in_user_id_40b7fe_idx'),
        ),
        migrations.RemoveField(
            model_name='interventionevaluation',
            name='is_delayed',
        ),
        migrations.RemoveField(
            model_name='interventionevaluation',
            name='skipped',
        ),
    ]
