# Generated by Django 6.0.3 on 2026-08-11 12:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('feedback', '0002_alter_interventionevaluation_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interventionevaluation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intervention_evaluations', to='accounts.anonymoususer'),
        ),
    ]
