# Generated by Django 6.0.3 on 2026-08-15 01:20

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('feedback', '0002_alter_interventionevaluation_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NightlyEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('for_date', models.DateField(help_text='평가 대상이 되는 밤의 날짜')),
                ('sound_session_id', models.PositiveIntegerField(blank=True, null=True)),
                ('relaxation_session_id', models.PositiveIntegerField(blank=True, null=True)),
                ('sleep_latency', models.CharField(blank=True, choices=[('under_15min', '15분 이내'), ('15_30min', '15-30분'), ('30_60min', '30-60분'), ('over_60min', '60분 초과'), ('unknown', '잘 모르겠어요')], help_text='잠드는 데 걸린 시간', max_length=20, null=True)),
                ('discomfort_after', models.PositiveSmallIntegerField(blank=True, help_text='다음날 회상한 이명 불편도 (1~5)', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('anxiety_after', models.PositiveSmallIntegerField(blank=True, help_text='다음날 회상한 불안 정도 (1~5)', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('current_fatigue', models.PositiveSmallIntegerField(blank=True, help_text='현재 피로도 (1~5)', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('note', models.CharField(blank=True, help_text='한 줄 메모 (선택)', max_length=200)),
                ('routine_helpfulness', models.PositiveSmallIntegerField(blank=True, help_text='어젯밤 수면 준비가 도움이 된 정도 (1~5)', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('sound_reactions', models.JSONField(blank=True, default=list, help_text='SoundReaction 값의 리스트 (복수 선택 가능)')),
                ('status', models.CharField(choices=[('pending', '평가 대기'), ('evaluated', '평가 완료'), ('expired', '미응답(24시간 경과)')], db_index=True, default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('evaluated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': '밤 단위 평가',
                'verbose_name_plural': '밤 단위 평가 목록',
                'ordering': ['-for_date'],
            },
        ),
        migrations.RemoveIndex(
            model_name='interventionevaluation',
            name='feedback_in_user_id_40b7fe_idx',
        ),
        migrations.RemoveConstraint(
            model_name='interventionevaluation',
            name='feedback_one_evaluation_per_session',
        ),
        migrations.AddField(
            model_name='nightlyevaluation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nightly_evaluations', to='accounts.anonymoususer'),
        ),
        migrations.RemoveField(
            model_name='interventionevaluation',
            name='user',
        ),
        migrations.AddIndex(
            model_name='nightlyevaluation',
            index=models.Index(fields=['user', '-for_date'], name='feedback_ni_user_id_17f132_idx'),
        ),
        migrations.AddConstraint(
            model_name='nightlyevaluation',
            constraint=models.UniqueConstraint(fields=('user', 'for_date'), name='feedback_one_nightly_evaluation_per_night'),
        ),
        migrations.DeleteModel(
            name='InterventionEvaluation',
        ),
    ]
