# Generated by Django 6.0.3 on 2026-08-15 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('feedback', '0003_nightlyevaluation_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='nightlyevaluation',
            options={'ordering': ['-created_at'], 'verbose_name': '세션 결과 평가', 'verbose_name_plural': '세션 결과 평가 목록'},
        ),
        migrations.RemoveConstraint(
            model_name='nightlyevaluation',
            name='feedback_one_nightly_evaluation_per_night',
        ),
        migrations.AlterField(
            model_name='nightlyevaluation',
            name='for_date',
            field=models.DateField(help_text='평가 대상 세션이 실행된 날짜'),
        ),
        migrations.AddIndex(
            model_name='nightlyevaluation',
            index=models.Index(fields=['user', 'status'], name='feedback_ni_user_id_ca6767_idx'),
        ),
        migrations.AddIndex(
            model_name='nightlyevaluation',
            index=models.Index(fields=['sound_session_id'], name='feedback_ni_sound_s_b698f6_idx'),
        ),
        migrations.AddIndex(
            model_name='nightlyevaluation',
            index=models.Index(fields=['relaxation_session_id'], name='feedback_ni_relaxat_fe1231_idx'),
        ),
    ]
