# Generated by Django 6.0.3 on 2026-08-18 01:56

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
        ("feedback", "0004_alter_nightlyevaluation_options_and_more"),
        ("relaxtion", "0001_initial"),
        ("sound", "0006_alter_soundsession_fallback_sound_and_more"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="nightlyevaluation",
            name="feedback_ni_sound_s_b698f6_idx",
        ),
        migrations.RemoveIndex(
            model_name="nightlyevaluation",
            name="feedback_ni_relaxat_fe1231_idx",
        ),

        # 기존 IntegerField의 데이터를 유지한 채 필드명 변경
        migrations.RenameField(
            model_name="nightlyevaluation",
            old_name="sound_session_id",
            new_name="sound_session",
        ),
        migrations.RenameField(
            model_name="nightlyevaluation",
            old_name="relaxation_session_id",
            new_name="relaxation_session",
        ),

        # 기존 숫자 PK 값을 실제 ForeignKey로 전환
        migrations.AlterField(
            model_name="nightlyevaluation",
            name="sound_session",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="nightly_evaluations",
                to="sound.soundsession",
            ),
        ),
        migrations.AlterField(
            model_name="nightlyevaluation",
            name="relaxation_session",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="nightly_evaluations",
                to="relaxtion.relaxationsession",
            ),
        ),

        migrations.AlterField(
            model_name="nightlyevaluation",
            name="routine_helpfulness",
            field=models.PositiveSmallIntegerField(
                blank=True,
                help_text="이완 활동이 수면 준비에 도움이 된 정도 (1~5)",
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(5),
                ],
            ),
        ),

        migrations.AddIndex(
            model_name="nightlyevaluation",
            index=models.Index(
                fields=["sound_session"],
                name="feedback_ni_sound_s_b698f6_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="nightlyevaluation",
            index=models.Index(
                fields=["relaxation_session"],
                name="feedback_ni_relaxat_fe1231_idx",
            ),
        ),
    ]